version: '3.8'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - fidecloud
    volumes:
      - auth-db:/var/lib/postgresql/gui

  auth-db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - fidecloud
  web:
    depends_on:
      - auth-db
    build: ./
    ports:
      - 50051:50051
    env_file:
      - .env.dev
      - .env.local
    working_dir: /authentication-service
    volumes:
      - .:/authentication-service
    command: "npm run start"
    networks:
      - fidecloud

volumes:
  auth-db:

networks:
  fidecloud:
    driver: bridge
